"""Add time change and cancellation tracking fields

Revision ID: 18a74d6994eb
Revises: 18a4e23bc91a
Create Date: 2026-01-06 13:12:48.367346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18a74d6994eb'
down_revision = '18a4e23bc91a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_preferred_time', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('time_change_reason', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('cancellation_reason', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('cancelled_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('cancelled_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['cancelled_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('cancelled_by')
        batch_op.drop_column('cancelled_at')
        batch_op.drop_column('cancellation_reason')
        batch_op.drop_column('time_change_reason')
        batch_op.drop_column('original_preferred_time')

    # ### end Alembic commands ###
