"""Add service_id foreign key to bookings table2

Revision ID: 21c1134e98ce
Revises: 62635cf5643b
Create Date: 2025-12-24 20:06:56.227104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21c1134e98ce'
down_revision = '62635cf5643b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_bookings_service_id_services'), type_='foreignkey')
        batch_op.drop_column('service_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_bookings_service_id_services'), 'services', ['service_id'], ['id'])

    # ### end Alembic commands ###
