"""Update Quote model

Revision ID: b476d9ef7d22
Revises: e7da901ef858
Create Date: 2025-12-27 15:33:59.605866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b476d9ef7d22'
down_revision = 'e7da901ef858'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quote_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_time', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('has_conflict', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('conflict_checked_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('cancelled_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.Enum('PENDING', 'SENT', 'ACCEPTED', 'REJECTED', 'CANCELLED', name='quotestatus'),
               existing_nullable=False)
        batch_op.create_index('idx_quote_datetime', ['event_date', 'event_time', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_quote_requests_client_email'), ['client_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_quote_requests_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_quote_requests_event_date'), ['event_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_quote_requests_event_time'), ['event_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_quote_requests_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quote_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quote_requests_status'))
        batch_op.drop_index(batch_op.f('ix_quote_requests_event_time'))
        batch_op.drop_index(batch_op.f('ix_quote_requests_event_date'))
        batch_op.drop_index(batch_op.f('ix_quote_requests_created_at'))
        batch_op.drop_index(batch_op.f('ix_quote_requests_client_email'))
        batch_op.drop_index('idx_quote_datetime')
        batch_op.alter_column('status',
               existing_type=sa.Enum('PENDING', 'SENT', 'ACCEPTED', 'REJECTED', 'CANCELLED', name='quotestatus'),
               type_=sa.VARCHAR(length=8),
               existing_nullable=False)
        batch_op.drop_column('cancelled_at')
        batch_op.drop_column('conflict_checked_at')
        batch_op.drop_column('has_conflict')
        batch_op.drop_column('event_time')

    # ### end Alembic commands ###
